### ISSUE TITLE
[FAQ] Light color openstreetmap tile

### ISSUE THREAD

**Issue by kirantpatil** [kambrium/staticmapservice#4]
Hi,

Is there a light color openstreetmap tile as shown below ?

![Screenshot from 2019-11-08 13-22-56](https://user-images.githubusercontent.com/1178055/68459331-135e0700-022b-11ea-91e3-2fdbd63c497d.png)

Current tile: 
--------------
![osm_polyline_with_marker](https://user-images.githubusercontent.com/1178055/68459387-47392c80-022b-11ea-9d7c-0cc0a8e8affc.png)

Thanks.

**Comment by kambrium** [comment]
CARTO (https://carto.com) offers a light grey basemap service. As far as I know this is licensed under CC BY 3.0 (please doublecheck) and based on OSM data. Just edit `config.py` so that it points to CARTO's tile server.

```
#TILE_SERVER = 'http://a.tile.osm.org/{z}/{x}/{y}.png'
TILE_SERVER = 'http://basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png'
```

The sample request `http://127.0.0.1:5000/?w=400&h=300&z=9&marker=coords:48.25,11.22|diam:10|color:%233F33FF&center=48,11.7` now returns the following image.

![grafik](https://user-images.githubusercontent.com/11823636/68463896-e18b7700-020f-11ea-8118-e28286363d06.png)

If you don't like this map style, have a look at the providers used by QGIS: https://raw.githubusercontent.com/klakar/QGIS_resources/master/collections/Geosupportsystem/python/qgis_basemaps.py. Another good source for tile servers is https://wiki.openstreetmap.org/wiki/Tile_servers.

Does this solve your problem?

**Comment by kirantpatil** [comment]
Dear @kambrium,

This is what I wanted.

I will check the license once again.

Thanks a lot.

Kiran.

**Comment by kambrium** [comment]
Glad to hear!
May I ask you in what context you're currently using staticmapservice? Business or private project? I'm just curious how the software is being used.

**Comment by kirantpatil** [comment]
Yeah, right now it is for private.

We are trying to showcase alternative solution to client if they don't want google staticmap service.

Thanks.

**Comment by kambrium** [comment]
Great, thanks!
